Fix CI pre-commit check failure. (#1195)
* Fix CI and add memory monitoring

* minor scripts improvements

* Update .github/workflows/pre-commit.yml

resolve boyue's comment.

Co-authored-by: Boyue Li <liboyue@users.noreply.github.com>

* make monitor process non-critical upon failure

---------

Co-authored-by: Boyue Li <liboyue@users.noreply.github.com>

diff --git a/.github/workflows/pre-commit.yml b/.github/workflows/pre-commit.yml
--- a/.github/workflows/pre-commit.yml
+++ b/.github/workflows/pre-commit.yml
@@ -16,5 +16,21 @@ jobs:
       # TODO(markblee): Remove gcp,vertexai_tensorboard from CI. (needed by pytype)
       - run: pip install '.[core,dev,grain,gcp,vertexai_tensorboard,open_api]'
       # pylint uses approx 12GB of memory during this run, look into split to decrease?
-      - run: pre-commit run --all-files
+      - run: |
+          # Start memory monitor as a background process.
+          { .github/scripts/monitor_memory.sh & } || true
+          MONITOR_PID=$!
+          # A short sleep to wait for monitor process to start.
+          sleep 1
+
+          # Start pre-commit check.
+          echo "====== Starting pre-commit... ======"
+          pre-commit run --all-files
+          echo "====== pre-commit completed. ======"
+
+          # Clean up memory monitor process.
+          if kill -0 $MONITOR_PID 2>/dev/null; then
+            echo "Manually stopping monitor process..."
+            kill $MONITOR_PID || true
+          fi
       - run: pytype -j auto .
